# Generated by Django 5.2.17 on 2026-08-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('referral_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('binary_pair_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('daily_capping', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
