# Generated by Django 5.2.17 on 2026-09-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DEVELOPER', 'System Developer'), ('ADMIN', 'Platform Owner / Administrator'), ('MEMBER', 'Member')], default='MEMBER', max_length=15),
        ),
    ]
