# Generated by Django 5.2.17 on 2026-09-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='back_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='front_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
